#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "radarr"
name = "Radarr"
description.en = "Movie collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de filmothèque pour utilisateurs de Usenet et BitTorrent"

version = "5.28.0.10274~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://radarr.video"
admindoc = "https://wiki.servarr.com/Radarr"
code = "https://github.com/Radarr/Radarr"
fund = "https://radarr.video/donate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["armhf", "arm64", "amd64", "i386"]
multi_instance = true

ldap = false
sso = "not_relevant"

disk = "300M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/radarr"

    [install.init_main_permission]
    type = "group"
    help.en = "Logging in is disabled for Radarr on YunoHost, use this permission to manage who will have access."
    help.fr = "La connexion est désactivée pour Radarr sur YunoHost, utilisez cette permission pour gérer qui y aura accès."

[resources]
    [resources.sources.main]
    armhf.url = "https://github.com/Radarr/Radarr/releases/download/v5.28.0.10274/Radarr.master.5.28.0.10274.linux-core-arm.tar.gz"
    armhf.sha256 = "657072736c68c0d949243d687b20d54e7a2a05822ddd3276f767a1fac18fb21a"
    arm64.url = "https://github.com/Radarr/Radarr/releases/download/v5.28.0.10274/Radarr.master.5.28.0.10274.linux-core-arm64.tar.gz"
    arm64.sha256 = "823dd22e470fa814a28156599ff5eaa2aaddfff987c555790c61bd4332fffb67"
    amd64.url = "https://github.com/Radarr/Radarr/releases/download/v5.28.0.10274/Radarr.master.5.28.0.10274.linux-core-x64.tar.gz"
    amd64.sha256 = "4f19773b30d71063999ea53ea923994089448c391c2346d26eb54e77bb82d734"
    i386.url = "https://github.com/Radarr/Radarr/releases/download/v5.28.0.10274/Radarr.master.5.28.0.10274.linux-core-x86.tar.gz"
    i386.sha256 = "5f7b5938e8ff7bb56b852f9c47bff43480808102a51746168cfed03f635aa35e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
    autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"
    autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
    autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]

    [resources.apt]
    packages = "curl, mediainfo, sqlite3"
